import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { api } from '../lib/api';
import type { DashboardSummary } from '../types';
import { Notice } from '../components/Notice';
import { Spinner } from '../components/Spinner';
import { TierBadge } from '../components/TierBadge';

export function DashboardPage() {
  const [data, setData] = useState<DashboardSummary | null>(null); const [error, setError] = useState('');
  useEffect(() => { void api.dashboard.summary().then(setData).catch((e: Error) => setError(e.message)); }, []);
  if (error) return <Page title="Dashboard"><Notice kind="error">{error}</Notice></Page>;
  if (!data) return <div className="center-content"><Spinner /></div>;
  return <Page title="Good shift, team." subtitle="A live view of the loyalty programme at the counter."><div className="stat-grid"><Stat label="Total members" value={data.totalMembers.toLocaleString()} detail="Active loyalty profiles" /><Stat label="Points issued" value={data.pointsIssued.toLocaleString()} detail="Lifetime earning events" /><Stat label="Points redeemed" value={data.pointsRedeemed.toLocaleString()} detail="Confirmed redemptions" /><Stat label="Platinum members" value={(data.membersByTier.PLATINUM ?? 0).toLocaleString()} detail="Current tier" /></div><div className="content-grid two"><section className="panel"><div className="panel-head"><div><span className="eyebrow">Member mix</span><h2>Tier distribution</h2></div><Link to="/app/members" className="text-link">View members →</Link></div><div className="tier-summary"><TierLine label="Platinum" value={data.membersByTier.PLATINUM ?? 0} total={data.totalMembers} tier="PLATINUM" /><TierLine label="Gold" value={data.membersByTier.GOLD ?? 0} total={data.totalMembers} tier="GOLD" /><TierLine label="Silver" value={data.membersByTier.SILVER ?? 0} total={data.totalMembers} tier="SILVER" /><TierLine label="Bronze" value={data.membersByTier.BRONZE ?? 0} total={data.totalMembers} tier="BRONZE" /></div></section><section className="panel"><div className="panel-head"><div><span className="eyebrow">Latest</span><h2>Recent purchases</h2></div></div><div className="activity-list">{data.recentPurchases.length ? data.recentPurchases.slice(0, 5).map(item => <div className="activity-row" key={item.id}><div><strong>{item.member.fullName}</strong><span>₹{item.amount} · {item.pointsEarned} points</span></div><TierBadge tier={item.member.currentTier} /></div>) : <Empty text="No purchases recorded yet." />}</div></section></div><div className="content-grid two"><section className="panel"><div className="panel-head"><div><span className="eyebrow">Latest</span><h2>Recent redemptions</h2></div></div><div className="activity-list">{data.recentRedemptions.length ? data.recentRedemptions.slice(0, 5).map(item => <div className="activity-row" key={item.id}><div><strong>{item.member.fullName}</strong><span>{item.reward.name} · {item.pointsUsed} points</span></div><span className="muted-text">{new Date(item.createdAt).toLocaleDateString()}</span></div>) : <Empty text="No redemptions recorded yet." />}</div></section><section className="panel accent-panel"><span className="eyebrow">Counter focus</span><h2>Keep balance changes traceable.</h2><p>Every purchase and redemption creates a ledger entry with the resulting balance, so staff can verify what happened without manual reconstruction.</p><Link to="/app/members" className="button primary">Find a member</Link></section></div></Page>;
}

function Stat({ label, value, detail }: { label: string; value: string; detail: string }) { return <div className="stat-card"><span>{label}</span><strong>{value}</strong><small>{detail}</small></div>; }
function TierLine({ label, value, total, tier }: { label: string; value: number; total: number; tier: 'PLATINUM' | 'GOLD' | 'SILVER' | 'BRONZE' }) { const width = total ? Math.max(2, Math.round((value / total) * 100)) : 0; return <div className="tier-line"><div className="tier-line-label"><TierBadge tier={tier} /><strong>{value}</strong></div><div className="bar"><span className={`bar-${tier.toLowerCase()}`} style={{ width: `${width}%` }} /></div></div>; }
function Empty({ text }: { text: string }) { return <div className="empty-state compact">{text}</div>; }
function Page({ title, subtitle, children }: { title: string; subtitle?: string; children: React.ReactNode }) { return <div className="page"><div className="page-head"><div><h1>{title}</h1>{subtitle && <p>{subtitle}</p>}</div></div>{children}</div>; }
