import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { api } from '../lib/api';
import { Notice } from '../components/Notice';
import { Spinner } from '../components/Spinner';
import { TierBadge } from '../components/TierBadge';
import type { Member } from '../types';

interface ListResult { items: Member[]; page: number; pageSize: number; total: number; totalPages: number; hasNext: boolean; hasPrevious: boolean; }

export function MembersPage() {
  const [result, setResult] = useState<ListResult | null>(null); const [search, setSearch] = useState(''); const [sortBy, setSortBy] = useState('createdAt'); const [sortOrder, setSortOrder] = useState('desc'); const [page, setPage] = useState(1); const [error, setError] = useState(''); const [showCreate, setShowCreate] = useState(false);
  const load = async () => { setError(''); try { const data = await api.members.list({ search, page, pageSize: 20, sortBy, sortOrder }); setResult(data as ListResult); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load members.'); } };
  useEffect(() => { void load(); }, [page, sortBy, sortOrder]);
  useEffect(() => { const id = window.setTimeout(() => { setPage(1); void load(); }, 300); return () => window.clearTimeout(id); }, [search]);
  const countLabel = useMemo(() => result ? `${result.total.toLocaleString()} member${result.total === 1 ? '' : 's'}` : '', [result]);
  return <div className="page"><div className="page-head"><div><span className="eyebrow">Directory</span><h1>Members</h1><p>Search by phone or name. Every result comes from the server.</p></div><button className="button primary" onClick={() => setShowCreate(true)}>+ Add member</button></div>{error && <Notice kind="error">{error}</Notice>}<section className="panel"><div className="toolbar"><label className="search-field"><span>⌕</span><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search phone or name…" /></label><div className="toolbar-controls"><select value={sortBy} onChange={e => { setSortBy(e.target.value); setPage(1); }} aria-label="Sort field"><option value="createdAt">Newest</option><option value="name">Name</option><option value="phone">Phone</option><option value="tier">Tier</option><option value="balance">Balance</option><option value="lifetimeEarnedPoints">Lifetime points</option></select><button className="button ghost" onClick={() => setSortOrder(v => v === 'asc' ? 'desc' : 'asc')}>{sortOrder === 'asc' ? '↑ Asc' : '↓ Desc'}</button></div></div>{!result ? <div className="empty-state"><Spinner label="Loading members…" /></div> : result.items.length === 0 ? <div className="empty-state"><strong>No members found</strong><span>Try a different phone/name search or add a member.</span></div> : <><div className="table-wrap"><table><thead><tr><th>Name</th><th>Phone</th><th>Tier</th><th>Balance</th><th>Lifetime</th><th>Joined</th><th /></tr></thead><tbody>{result.items.map(member => <tr key={member.id}><td><Link className="table-primary" to={`/app/members/${member.id}`}>{member.fullName}</Link><span className="table-secondary">{member.email || 'No email'}</span></td><td>{member.phoneNumber}</td><td><TierBadge tier={member.currentTier} /></td><td><strong>{member.currentPointsBalance}</strong> pts</td><td>{member.lifetimeEarnedPoints} pts</td><td>{new Date(member.createdAt).toLocaleDateString()}</td><td><Link className="text-link" to={`/app/members/${member.id}`}>Open</Link></td></tr>)}</tbody></table></div><div className="pagination"><span>{countLabel}</span><div><button className="button ghost" disabled={!result.hasPrevious} onClick={() => setPage(v => v - 1)}>Previous</button><span>Page {result.page} of {Math.max(result.totalPages, 1)}</span><button className="button ghost" disabled={!result.hasNext} onClick={() => setPage(v => v + 1)}>Next</button></div></div></>}</section>{showCreate && <CreateMemberModal onClose={() => setShowCreate(false)} onCreated={async () => { setShowCreate(false); setPage(1); await load(); }} />}</div>;
}

function CreateMemberModal({ onClose, onCreated }: { onClose: () => void; onCreated: () => Promise<void> }) {
  const [form, setForm] = useState({ fullName: '', phoneNumber: '', email: '' }); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  async function submit(event: React.FormEvent) { event.preventDefault(); setBusy(true); setError(''); try { await api.members.create(form); await onCreated(); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to create member.'); } finally { setBusy(false); } }
  return <div className="modal-backdrop" onMouseDown={event => { if (event.currentTarget === event.target) onClose(); }}><div className="modal"><div className="modal-head"><div><span className="eyebrow">New profile</span><h2>Add member</h2></div><button className="icon-button" onClick={onClose} aria-label="Close">×</button></div>{error && <Notice kind="error">{error}</Notice>}<form className="stack-form" onSubmit={submit}><label>Full name<input value={form.fullName} onChange={e => setForm({ ...form, fullName: e.target.value })} required /></label><label>Phone number<input value={form.phoneNumber} onChange={e => setForm({ ...form, phoneNumber: e.target.value })} placeholder="+91 90000 12345" required /></label><label>Email <span className="muted-text">optional</span><input type="email" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} /></label><div className="modal-actions"><button type="button" className="button ghost" onClick={onClose}>Cancel</button><button className="button primary" disabled={busy}>{busy ? 'Saving…' : 'Create member'}</button></div></form></div></div>;
}
